name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  evaluate-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install Nix
        uses: cachix/install-nix-action@v31

      - name: Configure Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v13

      - name: Run flake checks
        run: nix flake check

      - name: Evaluate packages for all supported systems
        run: |
          nix eval .#packages --apply '
            builtins.mapAttrs
              (system: pkgs: {
                stable = pkgs.vscode.version;
                insiders = pkgs.vscode-insiders.version;
              })
          '

      - name: Build Linux packages
        run: nix build .#vscode .#vscode-insiders --no-link
